### ISSUE TITLE
Home assitant docker , integration for Shield tv pro

### ISSUE THREAD

**Issue by nyok92** [deviant-aut/HA-androidtv11#8]
Logger: homeassistant.helpers.integration_platform
Source: loader.py:589
First occurred: 17:27:27 (6 occurrences)
Last logged: 17:27:27

Unexpected error importing androidtv/diagnostics.py
Unexpected error importing androidtv/logbook.py
Unexpected error importing androidtv/system_health.py
Unexpected error importing androidtv/media_source.py
Unexpected error importing androidtv/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 34, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 572, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 589, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.HA-androidtv11.recorder'

**Comment by nyok92** [comment]
Fixed by renaming HA-androidtv folder to androidtv
